{% set name = "dulwich" %}
{% set version = "1.2.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1278d8ddb0a92fa4bc9f2e9b14edf0a2e140248bccc4c7c9752a1390e2ab4c64
  patches:
    - find_testdata.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - setuptools >=77.0.0
    - setuptools-rust
  run:
    - python
    - urllib3 >=2.2.2
    - typing_extensions >=4.6.0  # [py<312]
  run_constrained:
    # https
    - urllib3 >=2.2.2
    # hypothesis
    - hypothesis >=6


{% set ignore_tests = "" %}
# upstream bug: ObjectFormat not imported in swift.py
{% set ignore_tests = ignore_tests ~ " --ignore=tests/contrib/test_swift.py" %}
# upstream bug: ObjectFormat not imported in swift.py
{% set ignore_tests = ignore_tests ~ " --ignore=tests/contrib/test_swift_smoke.py" %}
# source code compliance tests require source code in $SRC_DIR
{% set ignore_tests = ignore_tests ~ " --ignore=tests/test_source.py" %}
# missing dependency - merge3
{% set ignore_tests = ignore_tests ~ " --ignore=tests/test_rerere.py" %}
# TypeError: pack index v1 only supports SHA-1 names
{% set ignore_tests = ignore_tests ~ " --deselect=tests/test_sha256_pack.py::SHA256PackTests::test_pack_index_v1_with_sha256" %}
# Permission denied: '.git/hooks/pre-commit'
{% set ignore_tests = ignore_tests ~ " --deselect=tests/test_repository.py::RepositoryRootTests::test_shell_hook_pre_commit_add_files" %}
# ConnectionRefusedError: [Errno 111] Connection refused
{% set ignore_tests = ignore_tests ~ " --deselect=tests/compat/test_partial_clone.py::PartialCloneClientTestCase::test_clone_with_filter" %}
{% set ignore_tests = ignore_tests ~ " --deselect=tests/compat/test_partial_clone.py::PartialCloneClientTestCase::test_fetch_with_blob_none_filter" %}
# missing optional dependency - gpg
{% set ignore_tests = ignore_tests ~ " --ignore=tests/test_signature.py" %}

test:
  source_files:
    - tests
    - testdata
  requires:
    - pip
    - pytest
    - gevent
    - geventhttpclient
    - setuptools >=17.1
  commands:
    - pip check
    # Cannot test windows due to source location dependency
    - cd $SRC_DIR && pytest -vv tests {{ ignore_tests }}  # [not win]
  imports:
    - dulwich
    - dulwich.tests
    - dulwich.tests.utils
    - dulwich.archive
    - dulwich.client
    - dulwich.config
    - dulwich.diff_tree
    - dulwich.errors
    - dulwich.file
    - dulwich.hooks
    - dulwich.ignore
    - dulwich.index
    - dulwich.object_store
    - dulwich.objects
    - dulwich.objectspec
    - dulwich.pack
    - dulwich.patch
    - dulwich.protocol
    - dulwich.reflog
    - dulwich.refs
    - dulwich.repo
    - dulwich.server
    - dulwich.walk
    - dulwich.web

about:
  home: https://www.dulwich.io
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: Python Git Library
  description: |
    Python implementation of the Git file formats and protocols, without the need to have git installed.
    All functionality is available in pure Python. Optional C extensions can be built for improved performance.
    The project is named after the part of London that Mr. and Mrs. Git live in in the particular Monty Python sketch.
  doc_url: https://www.dulwich.io/docs
  dev_url: https://github.com/jelmer/dulwich

extra:
  recipe-maintainers:
    - mikofski
