{% set name = "dulwich" %}
{% set version = "0.22.7" %}
{% set sha256 = "d53935832dd182d4c1415042187093efcee988af5cd397fb1f394f5bb27f0707" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools >=61.2
    - wheel
    - setuptools-rust
  run:
    - python
    - urllib3 >=1.25

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - dulwich
    - dulwich.tests
    - dulwich.tests.compat
    - dulwich.tests.utils
    - dulwich.archive
    - dulwich.client
    - dulwich.config
    - dulwich.diff_tree
    - dulwich.errors
    - dulwich.file
    - dulwich.hooks
    - dulwich.ignore
    - dulwich.index
    - dulwich.object_store
    - dulwich.objects
    - dulwich.objectspec
    - dulwich.pack
    - dulwich.patch
    - dulwich.protocol
    - dulwich.reflog
    - dulwich.refs
    - dulwich.repo
    - dulwich.server
    - dulwich.walk
    - dulwich.web

about:
  home: https://www.dulwich.io/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: Python Git Library
  description: |
    Python implementation of the Git file formats and protocols, without the need to have git installed.
    All functionality is available in pure Python. Optional C extensions can be built for improved performance.
    The project is named after the part of London that Mr. and Mrs. Git live in in the particular Monty Python sketch.
  doc_url: https://www.dulwich.io/docs/
  dev_url: https://github.com/jelmer/dulwich

extra:
  recipe-maintainers:
    - mikofski
