{% set name = "dulwich" %}
{% set version = "0.25.0" %}
{% set sha256 = "baa84b539fea0e6a925a9159c3e0a1d08cceeea5260732b84200e077444a4b0e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools >=77.0.0
    - setuptools-rust
    - setuptools_rust
  run:
    - python
    - urllib3 >=2.2.2
    - typing_extensions >=4.6.0  # [py<312]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - dulwich
    - dulwich.tests
    - dulwich.tests.utils
    - dulwich.archive
    - dulwich.client
    - dulwich.config
    - dulwich.diff_tree
    - dulwich.errors
    - dulwich.file
    - dulwich.hooks
    - dulwich.ignore
    - dulwich.index
    - dulwich.object_store
    - dulwich.objects
    - dulwich.objectspec
    - dulwich.pack
    - dulwich.patch
    - dulwich.protocol
    - dulwich.reflog
    - dulwich.refs
    - dulwich.repo
    - dulwich.server
    - dulwich.walk
    - dulwich.web

about:
  home: https://www.dulwich.io/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: Python Git Library
  description: |
    Python implementation of the Git file formats and protocols, without the need to have git installed.
    All functionality is available in pure Python. Optional C extensions can be built for improved performance.
    The project is named after the part of London that Mr. and Mrs. Git live in in the particular Monty Python sketch.
  doc_url: https://www.dulwich.io/docs/
  dev_url: https://github.com/jelmer/dulwich

extra:
  recipe-maintainers:
    - mikofski
