{% set name = "dulwich" %}
{% set version = "0.25.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bca22c8aa4cbecbe8493b76e3fd6101513f09cf405cd9b92e116a48d9469e55a
  patches:
    - find_testdata.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools >=77.0.0
    - setuptools-rust
  run:
    - python
    - urllib3 >=2.2.2
    - typing_extensions >=4.6.0  # [py<312]

{% set ignore_tests = "" %}
# upstream bug: ObjectFormat not imported in swift.py
{% set ignore_tests = ignore_tests ~ " --ignore=tests/contrib/test_swift.py" %}
# upstream bug: ObjectFormat not imported in swift.py
{% set ignore_tests = ignore_tests ~ " --ignore=tests/contrib/test_swift_smoke.py" %}
# source code compliance tests require source code in $SRC_DIR
{% set ignore_tests = ignore_tests ~ " --ignore=tests/test_source.py" %}
# missing dependency - merge3
{% set ignore_tests = ignore_tests ~ " --ignore=tests/test_rerere.py" %}
# TypeError: pack index v1 only supports SHA-1 names
{% set ignore_tests = ignore_tests ~ " --deselect=tests/test_sha256_pack.py::SHA256PackTests::test_pack_index_v1_with_sha256" %}
# Permission denied: '.git/hooks/pre-commit'
{% set ignore_tests = ignore_tests ~ " --deselect=tests/test_repository.py::RepositoryRootTests::test_shell_hook_pre_commit_add_files" %}

test:
  source_files:
    - tests
    - testdata
  requires:
    - pip
    - pytest
    - gevent
    - geventhttpclient
    - setuptools >=17.1
  commands:
    - pip check
    # Cannot test windows due to source location dependency
    - cd $SRC_DIR && pytest -vv tests {{ ignore_tests }}  # [not win]
  imports:
    - dulwich
    - dulwich.tests
    - dulwich.tests.utils
    - dulwich.archive
    - dulwich.client
    - dulwich.config
    - dulwich.diff_tree
    - dulwich.errors
    - dulwich.file
    - dulwich.hooks
    - dulwich.ignore
    - dulwich.index
    - dulwich.object_store
    - dulwich.objects
    - dulwich.objectspec
    - dulwich.pack
    - dulwich.patch
    - dulwich.protocol
    - dulwich.reflog
    - dulwich.refs
    - dulwich.repo
    - dulwich.server
    - dulwich.walk
    - dulwich.web

about:
  home: https://www.dulwich.io/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: Python Git Library
  description: |
    Python implementation of the Git file formats and protocols, without the need to have git installed.
    All functionality is available in pure Python. Optional C extensions can be built for improved performance.
    The project is named after the part of London that Mr. and Mrs. Git live in in the particular Monty Python sketch.
  doc_url: https://www.dulwich.io/docs/
  dev_url: https://github.com/jelmer/dulwich

extra:
  recipe-maintainers:
    - mikofski
